import type { BeadColor } from '@/lib/bead/types';

// ========================================================
// 色板数据 — 所有颜色预设 rgb 字段
// ========================================================

function withRgb(c: { code: string; name: string; hex: string }): BeadColor {
  const h = c.hex.replace('#', '');
  return {
    code: c.code,
    name: c.name,
    hex: c.hex,
    rgb: [
      parseInt(h.substring(0, 2), 16),
      parseInt(h.substring(2, 4), 16),
      parseInt(h.substring(4, 6), 16),
    ],
  };
}

export interface BrandPalette {
  name: string;
  label: string;
  colors: BeadColor[];
}

const perlerColors59: BeadColor[] = [
  withRgb({ code: 'P01', name: 'White', hex: '#F1F1F1' }),
  withRgb({ code: 'P02', name: 'Cream', hex: '#F5F0D7' }),
  withRgb({ code: 'P03', name: 'Yellow', hex: '#FFE100' }),
  withRgb({ code: 'P04', name: 'Orange', hex: '#FF6B1A' }),
  withRgb({ code: 'P05', name: 'Red', hex: '#E10600' }),
  withRgb({ code: 'P06', name: 'Pink', hex: '#FF8DB5' }),
  withRgb({ code: 'P07', name: 'Purple', hex: '#73389D' }),
  withRgb({ code: 'P08', name: 'Dark Blue', hex: '#0F3B8C' }),
  withRgb({ code: 'P09', name: 'Light Blue', hex: '#3370C0' }),
  withRgb({ code: 'P10', name: 'Dark Green', hex: '#114938' }),
  withRgb({ code: 'P11', name: 'Light Green', hex: '#56BA9F' }),
  withRgb({ code: 'P12', name: 'Brown', hex: '#6B4226' }),
  withRgb({ code: 'P13', name: 'Gray', hex: '#9B9B9B' }),
  withRgb({ code: 'P14', name: 'Black', hex: '#212121' }),
  withRgb({ code: 'P15', name: 'Blush', hex: '#F9CDC6' }),
  withRgb({ code: 'P16', name: 'Butterscotch', hex: '#FEBF45' }),
  withRgb({ code: 'P17', name: 'Cheddar', hex: '#FEA324' }),
  withRgb({ code: 'P18', name: 'Peach', hex: '#FEB89F' }),
  withRgb({ code: 'P19', name: 'Toothpaste', hex: '#FFFEEC' }),
  withRgb({ code: 'P20', name: 'Raspberry', hex: '#EC86D0' }),
  withRgb({ code: 'P21', name: 'Hot Coral', hex: '#ED6356' }),
  withRgb({ code: 'P22', name: 'Sand', hex: '#CC9966' }),
  withRgb({ code: 'P23', name: 'Spice', hex: '#A56268' }),
  withRgb({ code: 'P24', name: 'Turquoise', hex: '#299D8F' }),
  withRgb({ code: 'P25', name: 'Kiwi Lime', hex: '#AFDCAB' }),
  withRgb({ code: 'P26', name: 'Prickly Pear', hex: '#C53B7A' }),
  withRgb({ code: 'P27', name: 'Pastel Yellow', hex: '#F6EB61' }),
  withRgb({ code: 'P28', name: 'Pastel Lavender', hex: '#A05EB5' }),
  withRgb({ code: 'P29', name: 'Pastel Blue', hex: '#41B6E6' }),
  withRgb({ code: 'P30', name: 'Pastel Green', hex: '#87D839' }),
  withRgb({ code: 'P31', name: 'Plum', hex: '#53447D' }),
  withRgb({ code: 'P32', name: 'Mulberry', hex: '#F1A7DC' }),
  withRgb({ code: 'P33', name: 'Tangerine', hex: '#F6AD4C' }),
  withRgb({ code: 'P34', name: 'Neon Orange', hex: '#FF671F' }),
  withRgb({ code: 'P35', name: 'Neon Pink', hex: '#FF34B3' }),
  withRgb({ code: 'P36', name: 'Neon Green', hex: '#73D33C' }),
  withRgb({ code: 'P37', name: 'Neon Yellow', hex: '#CEDC00' }),
  withRgb({ code: 'P38', name: 'Bright Green', hex: '#24DE5B' }),
  withRgb({ code: 'P39', name: 'Dark Spruce', hex: '#00685E' }),
  withRgb({ code: 'P40', name: 'Evergreen', hex: '#183028' }),
  withRgb({ code: 'P41', name: 'Fruit Punch', hex: '#FF6D6A' }),
  withRgb({ code: 'P42', name: 'Bubblegum', hex: '#FCBFA9' }),
  withRgb({ code: 'P43', name: 'Cotton Candy', hex: '#F7CED7' }),
  withRgb({ code: 'P44', name: 'Mint', hex: '#9EE5B0' }),
  withRgb({ code: 'P45', name: 'Sky', hex: '#8DC8E8' }),
  withRgb({ code: 'P46', name: 'Lagoon', hex: '#71D8BF' }),
  withRgb({ code: 'P47', name: 'Fawn', hex: '#E1C078' }),
  withRgb({ code: 'P48', name: 'Honey', hex: '#FFE780' }),
  withRgb({ code: 'P49', name: 'Tan', hex: '#7B4D35' }),
  withRgb({ code: 'P50', name: 'Silver', hex: '#A09F9D' }),
  withRgb({ code: 'P51', name: 'Gold Metallic', hex: '#DEB947' }),
  withRgb({ code: 'P52', name: 'Light Blue', hex: '#5390D1' }),
  withRgb({ code: 'P53', name: 'Blue', hex: '#147BD1' }),
  withRgb({ code: 'P54', name: 'Turquoise Blue', hex: '#00AED6' }),
  withRgb({ code: 'P55', name: 'Slate', hex: '#767777' }),
  withRgb({ code: 'P56', name: 'Mocha', hex: '#B58150' }),
  withRgb({ code: 'P57', name: 'Mahogany', hex: '#5C4738' }),
  withRgb({ code: 'P58', name: 'Toothpaste', hex: '#93C8D4' }),
  withRgb({ code: 'P59', name: 'Wisteria', hex: '#C5B4E3' }),
];

const perlerColors82: BeadColor[] = [
  ...perlerColors59,
  withRgb({ code: 'P60', name: 'Lavender', hex: '#A77BCA' }),
  withRgb({ code: 'P61', name: 'Iris', hex: '#64359B' }),
  withRgb({ code: 'P62', name: 'Midnight', hex: '#050849' }),
  withRgb({ code: 'P63', name: "Robin's Egg", hex: '#59D5D8' }),
  withRgb({ code: 'P64', name: 'Steel Blue', hex: '#48A9C5' }),
  withRgb({ code: 'P65', name: 'Teal', hex: '#00B2A9' }),
  withRgb({ code: 'P66', name: 'Frost', hex: '#99D6EA' }),
  withRgb({ code: 'P67', name: 'Marshmallow', hex: '#F3CFB3' }),
  withRgb({ code: 'P68', name: 'Ginger', hex: '#B86125' }),
  withRgb({ code: 'P81', name: 'Light Gray', hex: '#EEEEEE' }),
  withRgb({ code: 'P82', name: 'Dark Gray', hex: '#6B6B6B' }),
  withRgb({ code: 'P83', name: 'Charcoal', hex: '#484949' }),
  withRgb({ code: 'P84', name: 'Copper', hex: '#9A5516' }),
  withRgb({ code: 'P85', name: 'Magenta', hex: '#DB2152' }),
  withRgb({ code: 'P86', name: 'Fuchsia', hex: '#DA1884' }),
  withRgb({ code: 'P91', name: 'Parrot Green', hex: '#067C81' }),
  withRgb({ code: 'P92', name: 'Lipstick Red', hex: '#BA0C2F' }),
  withRgb({ code: 'P101', name: 'Pearl Light Blue', hex: '#7AAEA2' }),
  withRgb({ code: 'P102', name: 'Pearl Pink', hex: '#FAAA8D' }),
  withRgb({ code: 'P103', name: 'Pearl Purple', hex: '#AB2556' }),
  withRgb({ code: 'P104', name: 'Pearl White', hex: '#F2F0A1' }),
  withRgb({ code: 'P105', name: 'Pearl Silver', hex: '#BAB8A2' }),
  withRgb({ code: 'P106', name: 'Pearl Gray', hex: '#888B8D' }),
];

const hamaColors30: BeadColor[] = [
  withRgb({ code: 'H01', name: 'White', hex: '#ECEDED' }),
  withRgb({ code: 'H02', name: 'Cream', hex: '#F0E8B9' }),
  withRgb({ code: 'H03', name: 'Yellow', hex: '#F0B901' }),
  withRgb({ code: 'H04', name: 'Orange', hex: '#E64F27' }),
  withRgb({ code: 'H05', name: 'Red', hex: '#B63136' }),
  withRgb({ code: 'H06', name: 'Pink', hex: '#E1889F' }),
  withRgb({ code: 'H07', name: 'Purple', hex: '#694A82' }),
  withRgb({ code: 'H08', name: 'Dark Blue', hex: '#2C4690' }),
  withRgb({ code: 'H09', name: 'Light Blue', hex: '#305CB0' }),
  withRgb({ code: 'H10', name: 'Green', hex: '#256847' }),
  withRgb({ code: 'H11', name: 'Light Green', hex: '#49AE89' }),
  withRgb({ code: 'H12', name: 'Brown', hex: '#534137' }),
  withRgb({ code: 'H17', name: 'Grey', hex: '#83888A' }),
  withRgb({ code: 'H18', name: 'Black', hex: '#2E2F31' }),
  withRgb({ code: 'H20', name: 'Burgundy', hex: '#7F332A' }),
  withRgb({ code: 'H21', name: 'Tan', hex: '#A5693F' }),
  withRgb({ code: 'H22', name: 'Dark Red', hex: '#A52D36' }),
  withRgb({ code: 'H26', name: 'Flesh', hex: '#DE9B90' }),
  withRgb({ code: 'H27', name: 'Beige', hex: '#DEB48B' }),
  withRgb({ code: 'H28', name: 'Dark Green', hex: '#363F38' }),
  withRgb({ code: 'H29', name: 'Dark Pink', hex: '#B9395E' }),
  withRgb({ code: 'H30', name: 'Dark Brown', hex: '#592F38' }),
  withRgb({ code: 'H31', name: 'Steel Blue', hex: '#6797AE' }),
  withRgb({ code: 'H33', name: 'Neon Red', hex: '#FF3956' }),
  withRgb({ code: 'H43', name: 'Neon Yellow', hex: '#F0EA37' }),
  withRgb({ code: 'H44', name: 'Salmon', hex: '#EE6972' }),
  withRgb({ code: 'H45', name: 'Lavender', hex: '#886DB9' }),
  withRgb({ code: 'H46', name: 'Sky Blue', hex: '#629ED7' }),
  withRgb({ code: 'H47', name: 'Neon Green', hex: '#83CB70' }),
  withRgb({ code: 'H48', name: 'Neon Magenta', hex: '#CF70B7' }),
];

const hamaColors53: BeadColor[] = [
  ...hamaColors30,
  withRgb({ code: 'H49', name: 'Turquoise', hex: '#4998BC' }),
  withRgb({ code: 'H60', name: 'Gold', hex: '#F49422' }),
  withRgb({ code: 'H70', name: 'Pastel Lavender', hex: '#B6B6D4' }),
  withRgb({ code: 'H71', name: 'Dark Grey', hex: '#464541' }),
  withRgb({ code: 'H75', name: 'Light Brown', hex: '#BF7B4D' }),
  withRgb({ code: 'H76', name: 'Chocolate', hex: '#663317' }),
  withRgb({ code: 'H77', name: 'Ivory', hex: '#EDE7DF' }),
  withRgb({ code: 'H78', name: 'Peach', hex: '#FFC99A' }),
  withRgb({ code: 'H79', name: 'Terracotta', hex: '#F08643' }),
  withRgb({ code: 'H82', name: 'Plum', hex: '#962F5C' }),
  withRgb({ code: 'H83', name: 'Teal', hex: '#0178A4' }),
  withRgb({ code: 'H84', name: 'Olive', hex: '#8B924C' }),
  withRgb({ code: 'H95', name: 'Light Pink', hex: '#F8CCE0' }),
  withRgb({ code: 'H96', name: 'Light Purple', hex: '#D4B1E3' }),
  withRgb({ code: 'H97', name: 'Baby Blue', hex: '#A2D3FE' }),
  withRgb({ code: 'H98', name: 'Mint', hex: '#9ADBB1' }),
  withRgb({ code: 'H101', name: 'Pale Green', hex: '#A9C39B' }),
  withRgb({ code: 'H102', name: 'Forest Green', hex: '#356B2D' }),
  withRgb({ code: 'H103', name: 'Lemon', hex: '#FFE660' }),
  withRgb({ code: 'H104', name: 'Lime', hex: '#BCD122' }),
  withRgb({ code: 'H105', name: 'Apricot', hex: '#FFAC78' }),
  withRgb({ code: 'H106', name: 'Periwinkle', hex: '#CCC5ED' }),
  withRgb({ code: 'H107', name: 'Cornflower', hex: '#6A87C1' }),
];

const artkalColors: BeadColor[] = [
  withRgb({ code: 'S01', name: 'White', hex: '#FFFFFF' }),
  withRgb({ code: 'S77', name: 'Ghost White', hex: '#EFEFEF' }),
  withRgb({ code: 'S78', name: 'Ash Gray', hex: '#D1D1D1' }),
  withRgb({ code: 'S79', name: 'Light Gray', hex: '#BBBCBC' }),
  withRgb({ code: 'S07', name: 'Gray', hex: '#9B9B9B' }),
  withRgb({ code: 'S43', name: 'Dark Gray', hex: '#767777' }),
  withRgb({ code: 'S89', name: 'Charcoal Gray', hex: '#484949' }),
  withRgb({ code: 'S69', name: 'Mine Shaft', hex: '#23282B' }),
  withRgb({ code: 'S13', name: 'Black', hex: '#000000' }),
  withRgb({ code: 'S42', name: 'Silver', hex: '#A09F9D' }),
  withRgb({ code: 'S41', name: 'Copper', hex: '#9A5516' }),
  withRgb({ code: 'S52', name: 'Picasso', hex: '#F2F0A1' }),
  withRgb({ code: 'S29', name: 'Pastel Yellow', hex: '#F6EB61' }),
  withRgb({ code: 'S14', name: 'Sandstorm', hex: '#FAE053' }),
  withRgb({ code: 'S27', name: 'Yellow', hex: '#FFD100' }),
  withRgb({ code: 'S48', name: 'Corn', hex: '#FFC72C' }),
  withRgb({ code: 'S86', name: 'Goldenrod', hex: '#EAAA00' }),
  withRgb({ code: 'S90', name: 'Pastel Orange', hex: '#FFC56E' }),
  withRgb({ code: 'S03', name: 'Tangerine', hex: '#F6AD4C' }),
  withRgb({ code: 'S39', name: 'Yellow Orange', hex: '#ED8B00' }),
  withRgb({ code: 'S56', name: 'Bright Carrot', hex: '#FF6A13' }),
  withRgb({ code: 'S04', name: 'Orange', hex: '#FF671F' }),
  withRgb({ code: 'S66', name: 'Blaze Orange', hex: '#F4633A' }),
  withRgb({ code: 'S87', name: 'Coral Red', hex: '#FF6D6A' }),
  withRgb({ code: 'S02', name: 'Burning Sand', hex: '#FFA38B' }),
  withRgb({ code: 'S50', name: 'Mandys Pink', hex: '#FAAA8D' }),
  withRgb({ code: 'S35', name: 'Mona Lisa', hex: '#F7CED7' }),
  withRgb({ code: 'S28', name: 'Lily Pink', hex: '#EAB8E4' }),
  withRgb({ code: 'S40', name: 'Carnation Pink', hex: '#F1A7DC' }),
  withRgb({ code: 'S06', name: 'Raspberry Pink', hex: '#EC86D0' }),
  withRgb({ code: 'S25', name: 'Hot Pink', hex: '#FF34B3' }),
  withRgb({ code: 'S26', name: 'Magenta', hex: '#DB2152' }),
  withRgb({ code: 'S05', name: 'Tall Poppy', hex: '#E10600' }),
  withRgb({ code: 'S34', name: 'Red', hex: '#BA0C2F' }),
  withRgb({ code: 'S58', name: 'Paprika', hex: '#A50034' }),
  withRgb({ code: 'S38', name: 'Burgundy', hex: '#AB2556' }),
  withRgb({ code: 'S49', name: 'Mulberry Wood', hex: '#72195F' }),
  withRgb({ code: 'S88', name: 'Dark Pink', hex: '#DA1884' }),
  withRgb({ code: 'S67', name: 'Vanilla', hex: '#F3CFB3' }),
  withRgb({ code: 'S18', name: 'Sand', hex: '#CC9966' }),
  withRgb({ code: 'S65', name: 'Canary', hex: '#F3EA5D' }),
  withRgb({ code: 'S46', name: 'Bright Green', hex: '#73D33C' }),
  withRgb({ code: 'S08', name: 'Emerald', hex: '#24DE5B' }),
  withRgb({ code: 'S61', name: 'Key Lemon Pie', hex: '#CEDC00' }),
  withRgb({ code: 'S70', name: 'Dark Algae', hex: '#9BBC11' }),
  withRgb({ code: 'S55', name: 'Pistachio', hex: '#ADDC91' }),
  withRgb({ code: 'S21', name: 'Pastel Green', hex: '#87D839' }),
  withRgb({ code: 'S20', name: 'Green', hex: '#249E6B' }),
  withRgb({ code: 'S71', name: 'Jade Green', hex: '#00852B' }),
  withRgb({ code: 'S62', name: 'Green Tea', hex: '#007C58' }),
  withRgb({ code: 'S09', name: 'Dark Green', hex: '#00685E' }),
  withRgb({ code: 'S91', name: 'Brunswick Green', hex: '#183028' }),
  withRgb({ code: 'S33', name: 'Maverick', hex: '#C5B4E3' }),
  withRgb({ code: 'S60', name: 'Lavender', hex: '#A77BCA' }),
  withRgb({ code: 'S12', name: 'Pastel Lavender', hex: '#A05EB5' }),
  withRgb({ code: 'S23', name: 'Royal Purple', hex: '#64359B' }),
  withRgb({ code: 'S59', name: 'Butterfly Bush', hex: '#4A1F87' }),
  withRgb({ code: 'S22', name: 'Purple', hex: '#330072' }),
  withRgb({ code: 'S64', name: 'Black Rock', hex: '#050849' }),
  withRgb({ code: 'S44', name: 'Sky Blue', hex: '#8DC8E8' }),
  withRgb({ code: 'S10', name: 'Baby Blue', hex: '#41B6E6' }),
  withRgb({ code: 'S53', name: 'Blue Enchantress', hex: '#69B3E7' }),
  withRgb({ code: 'S54', name: 'Light Blue', hex: '#0090DA' }),
  withRgb({ code: 'S24', name: 'True Blue', hex: '#147BD1' }),
  withRgb({ code: 'S11', name: 'Dark Blue', hex: '#003399' }),
  withRgb({ code: 'S30', name: 'Shadow Green', hex: '#99D6EA' }),
  withRgb({ code: 'S31', name: 'Sea Mist', hex: '#9EE5B0' }),
  withRgb({ code: 'S37', name: 'Blue-Green', hex: '#71D8BF' }),
  withRgb({ code: 'S72', name: 'Light Sea Blue', hex: '#59D5D8' }),
  withRgb({ code: 'S45', name: 'Medium Turquoise', hex: '#00B2A9' }),
  withRgb({ code: 'S76', name: 'Sea Blue', hex: '#00AEC7' }),
  withRgb({ code: 'S73', name: 'Steel Blue', hex: '#48A9C5' }),
  withRgb({ code: 'S74', name: 'Azure', hex: '#00AED6' }),
  withRgb({ code: 'S75', name: 'Dark Steel Blue', hex: '#0085AD' }),
  withRgb({ code: 'S19', name: 'Bubble Gum', hex: '#FCBFA9' }),
  withRgb({ code: 'S32', name: 'Beeswax', hex: '#FFE780' }),
  withRgb({ code: 'S68', name: 'Tan', hex: '#E1C078' }),
  withRgb({ code: 'S17', name: 'Light Brown', hex: '#7B4D35' }),
  withRgb({ code: 'S16', name: 'Brown', hex: '#5C4738' }),
  withRgb({ code: 'S15', name: 'Redwood', hex: '#793E2C' }),
  withRgb({ code: 'S83', name: 'Sienna', hex: '#B86125' }),
  withRgb({ code: 'S47', name: 'Marigold', hex: '#B47E00' }),
  withRgb({ code: 'S80', name: 'Dark Olive', hex: '#999B30' }),
  withRgb({ code: 'S63', name: 'Metallic Gold', hex: '#B8860B' }),
  withRgb({ code: 'S36', name: 'Old Pink', hex: '#C9809E' }),
  withRgb({ code: 'S51', name: 'Spring Sun', hex: '#FCFBCD' }),
  withRgb({ code: 'S81', name: 'Deer', hex: '#CDB277' }),
  withRgb({ code: 'S82', name: 'Clay', hex: '#B58150' }),
  withRgb({ code: 'S84', name: 'Deep Chestnut', hex: '#AA5761' }),
  withRgb({ code: 'S85', name: 'Red Wine', hex: '#42031A' }),
  withRgb({ code: 'S57', name: 'Buccaneer', hex: '#A4493D' }),
  withRgb({ code: 'S92', name: 'Dandelion', hex: '#DEB947' }),
  withRgb({ code: 'S93', name: 'Pale Skin', hex: '#DAB698' }),
  withRgb({ code: 'S94', name: 'Warm Blush', hex: '#F4A999' }),
  withRgb({ code: 'S95', name: 'Salmon', hex: '#EE7D67' }),
  withRgb({ code: 'S96', name: 'Apricot', hex: '#F08661' }),
  withRgb({ code: 'S97', name: 'Papaya', hex: '#D4722A' }),
  withRgb({ code: 'S98', name: 'Himalaya Blue', hex: '#64ACDF' }),
  withRgb({ code: 'S99', name: 'Waterfall', hex: '#64C2DC' }),
  withRgb({ code: 'S100', name: 'Lagoon', hex: '#4F9FB3' }),
  withRgb({ code: 'S101', name: 'Electric Blue', hex: '#3196DD' }),
  withRgb({ code: 'S102', name: 'Pool Blue', hex: '#1B6CB6' }),
  withRgb({ code: 'S103', name: 'Caribbean Blue', hex: '#083980' }),
  withRgb({ code: 'S104', name: 'Deep Water', hex: '#0A668B' }),
  withRgb({ code: 'S105', name: 'Petrol Blue', hex: '#085B6E' }),
  withRgb({ code: 'S106', name: 'Wedgewood Blue', hex: '#004E78' }),
  withRgb({ code: 'S107', name: 'Pond Blue', hex: '#005574' }),
  withRgb({ code: 'S108', name: 'Seashell Beige', hex: '#CCBE80' }),
  withRgb({ code: 'S109', name: 'Beige', hex: '#A49350' }),
  withRgb({ code: 'S110', name: 'Beach Beige', hex: '#9E883C' }),
  withRgb({ code: 'S111', name: 'Caffe Latte', hex: '#766C2B' }),
  withRgb({ code: 'S112', name: 'Oaktree Brown', hex: '#795F26' }),
  withRgb({ code: 'S113', name: 'Khaki', hex: '#BAB8A2' }),
  withRgb({ code: 'S114', name: 'Light Greengray', hex: '#728C54' }),
  withRgb({ code: 'S115', name: 'Mossy Green', hex: '#7E7C44' }),
  withRgb({ code: 'S116', name: 'Earth Green', hex: '#64692E' }),
  withRgb({ code: 'S117', name: 'Sage Green', hex: '#4E582C' }),
  withRgb({ code: 'S118', name: 'Pinetree Green', hex: '#4A5E2D' }),
  withRgb({ code: 'S119', name: 'Frosty Blue', hex: '#71C452' }),
  withRgb({ code: 'S120', name: 'Polar Mint', hex: '#66CC99' }),
  withRgb({ code: 'S121', name: 'Celadon Green', hex: '#569A83' }),
  withRgb({ code: 'S122', name: 'Eucalyptus', hex: '#14C25B' }),
  withRgb({ code: 'S123', name: 'Clover Field', hex: '#18A818' }),
  withRgb({ code: 'S124', name: 'Pooltable Felt', hex: '#04552E' }),
  withRgb({ code: 'S125', name: 'Snake Green', hex: '#136B5A' }),
  withRgb({ code: 'S126', name: 'Dark Eucalyptus', hex: '#054641' }),
  withRgb({ code: 'S127', name: 'Marshmallow Rose', hex: '#D9B6D6' }),
  withRgb({ code: 'S128', name: 'Light Grape', hex: '#AD62A4' }),
  withRgb({ code: 'S129', name: 'Rosebud Pink', hex: '#E68CA3' }),
  withRgb({ code: 'S130', name: 'Fuchsia', hex: '#DE5479' }),
  withRgb({ code: 'S131', name: 'Candy Violet', hex: '#9E82BA' }),
  withRgb({ code: 'S132', name: 'Flamingo', hex: '#E8416B' }),
  withRgb({ code: 'S133', name: 'Pink Plum', hex: '#B7388F' }),
  withRgb({ code: 'S134', name: 'Amethyst', hex: '#581F7E' }),
  withRgb({ code: 'S135', name: 'Moonlight Blue', hex: '#8CA3D4' }),
  withRgb({ code: 'S136', name: 'Summer Rain', hex: '#9A9ACC' }),
  withRgb({ code: 'S137', name: 'Azure Blue', hex: '#5981C1' }),
  withRgb({ code: 'S138', name: 'Cornflower Blue', hex: '#4166B0' }),
  withRgb({ code: 'S139', name: 'Forget Me Not', hex: '#475FAB' }),
  withRgb({ code: 'S140', name: 'Indigo', hex: '#374593' }),
  withRgb({ code: 'S141', name: 'Horizon Blue', hex: '#3D56A5' }),
  withRgb({ code: 'S142', name: 'Cobalt', hex: '#294299' }),
  withRgb({ code: 'S143', name: 'Royal Blue', hex: '#25268A' }),
  withRgb({ code: 'S144', name: 'Marine', hex: '#1A2F6F' }),
  withRgb({ code: 'S145', name: 'Pale Yellow Moss', hex: '#D3C95D' }),
  withRgb({ code: 'S146', name: 'Bloodrose Red', hex: '#510918' }),
  withRgb({ code: 'S147', name: 'Spearmint', hex: '#64B39E' }),
  withRgb({ code: 'S148', name: 'Mocha', hex: '#634338' }),
  withRgb({ code: 'S149', name: 'Creme', hex: '#EDD39E' }),
  withRgb({ code: 'S150', name: 'Iris Violet', hex: '#6963AB' }),
  withRgb({ code: 'S151', name: 'Forest Green', hex: '#2B3F1F' }),
  withRgb({ code: 'S152', name: 'Lilac', hex: '#9791C5' }),
  withRgb({ code: 'S153', name: 'Pale Lilac', hex: '#B8BDE0' }),
  withRgb({ code: 'S154', name: 'Sahara Sand', hex: '#F9C898' }),
  withRgb({ code: 'S155', name: 'Sunkissed Teint', hex: '#C39069' }),
  withRgb({ code: 'S156', name: 'Steel Grey', hex: '#44505B' }),
  withRgb({ code: 'S157', name: 'Iron Grey', hex: '#3E4955' }),
  withRgb({ code: 'S158', name: 'Pepper', hex: '#202830' }),
  withRgb({ code: 'S159', name: 'Oslo Gray', hex: '#888B8D' }),
];

const mardColors291: BeadColor[] = [
  withRgb({ code: 'A1', name: 'Lemon Chiffon', hex: '#FAF4C8' }),
  withRgb({ code: 'A2', name: 'Light Yellow', hex: '#FFFFD5' }),
  withRgb({ code: 'A3', name: 'Pale Yellow', hex: '#FEFF8B' }),
  withRgb({ code: 'A4', name: 'Yellow', hex: '#FBED56' }),
  withRgb({ code: 'A5', name: 'Golden Yellow', hex: '#F4D738' }),
  withRgb({ code: 'A6', name: 'Orange', hex: '#FEAC4C' }),
  withRgb({ code: 'A7', name: 'Dark Orange', hex: '#FE8B4C' }),
  withRgb({ code: 'A8', name: 'Gold', hex: '#FFDA45' }),
  withRgb({ code: 'A9', name: 'Light Salmon', hex: '#FF995B' }),
  withRgb({ code: 'A10', name: 'Coral', hex: '#F77C31' }),
  withRgb({ code: 'A11', name: 'Peach', hex: '#FFDD99' }),
  withRgb({ code: 'A12', name: 'Light Salmon', hex: '#FE9F72' }),
  withRgb({ code: 'A13', name: 'Moccasin', hex: '#FFC365' }),
  withRgb({ code: 'A14', name: 'Tomato', hex: '#FD543D' }),
  withRgb({ code: 'A15', name: 'Lemon', hex: '#FFF365' }),
  withRgb({ code: 'A16', name: 'Pale Gold', hex: '#FFFF9F' }),
  withRgb({ code: 'A17', name: 'Khaki', hex: '#FFE36E' }),
  withRgb({ code: 'A18', name: 'Wheat', hex: '#FEBE7D' }),
  withRgb({ code: 'A19', name: 'Salmon', hex: '#FD7C72' }),
  withRgb({ code: 'A20', name: 'Goldenrod', hex: '#FFD568' }),
  withRgb({ code: 'A21', name: 'Pale Goldenrod', hex: '#FFE395' }),
  withRgb({ code: 'A22', name: 'Green Yellow', hex: '#F4F57D' }),
  withRgb({ code: 'A23', name: 'Bisque', hex: '#E6C9B7' }),
  withRgb({ code: 'A24', name: 'Green Yellow 2', hex: '#F7F8A2' }),
  withRgb({ code: 'A25', name: 'Navajo White', hex: '#FFD67D' }),
  withRgb({ code: 'A26', name: 'Saffron', hex: '#FFC830' }),
  withRgb({ code: 'B1', name: 'Lime', hex: '#E6EE31' }),
  withRgb({ code: 'B2', name: 'Green', hex: '#63F347' }),
  withRgb({ code: 'B3', name: 'Pale Green', hex: '#9EF780' }),
  withRgb({ code: 'B4', name: 'Lime Green', hex: '#5DE035' }),
  withRgb({ code: 'B5', name: 'Spring Green', hex: '#35E352' }),
  withRgb({ code: 'B6', name: 'Medium Aquamarine', hex: '#65E2A6' }),
  withRgb({ code: 'B7', name: 'Sea Green', hex: '#3DAF80' }),
  withRgb({ code: 'B8', name: 'Forest Green', hex: '#1C9C4F' }),
  withRgb({ code: 'B9', name: 'Dark Green', hex: '#27523A' }),
  withRgb({ code: 'B10', name: 'Aquamarine', hex: '#95D3C2' }),
  withRgb({ code: 'B11', name: 'Olive Drab', hex: '#5D722A' }),
  withRgb({ code: 'B12', name: 'Dark Green 2', hex: '#166F41' }),
  withRgb({ code: 'B13', name: 'Chartreuse', hex: '#CAEB7B' }),
  withRgb({ code: 'B14', name: 'Green Yellow', hex: '#ADE946' }),
  withRgb({ code: 'B15', name: 'Dark Olive', hex: '#2E5132' }),
  withRgb({ code: 'B16', name: 'Light Green', hex: '#C5ED9C' }),
  withRgb({ code: 'B17', name: 'Yellow Green', hex: '#9BB13A' }),
  withRgb({ code: 'B18', name: 'Lime 2', hex: '#E6EE49' }),
  withRgb({ code: 'B19', name: 'Teal Green', hex: '#24B88C' }),
  withRgb({ code: 'B20', name: 'Mint Cream', hex: '#C2F0CC' }),
  withRgb({ code: 'B21', name: 'Teal', hex: '#156A6B' }),
  withRgb({ code: 'B22', name: 'Dark Slate', hex: '#0B3C43' }),
  withRgb({ code: 'B23', name: 'Dark Olive 2', hex: '#303A21' }),
  withRgb({ code: 'B24', name: 'Pale Green 2', hex: '#EEFCA5' }),
  withRgb({ code: 'B25', name: 'Viridian', hex: '#4E846D' }),
  withRgb({ code: 'B26', name: 'Olive', hex: '#8D7A35' }),
  withRgb({ code: 'B27', name: 'Pale Green 3', hex: '#CCE1AF' }),
  withRgb({ code: 'B28', name: 'Sea Green 2', hex: '#9EE5B9' }),
  withRgb({ code: 'B29', name: 'Chartreuse 2', hex: '#C5E254' }),
  withRgb({ code: 'B30', name: 'Pale Green 4', hex: '#E2FCB1' }),
  withRgb({ code: 'B31', name: 'Light Green 2', hex: '#B0E792' }),
  withRgb({ code: 'B32', name: 'Olive Green', hex: '#9CAB5A' }),
  withRgb({ code: 'C1', name: 'Honeydew', hex: '#E8FFE7' }),
  withRgb({ code: 'C2', name: 'Pale Turquoise', hex: '#A9F9FC' }),
  withRgb({ code: 'C3', name: 'Light Sky Blue', hex: '#A0E2FB' }),
  withRgb({ code: 'C4', name: 'Deep Sky Blue', hex: '#41CCFF' }),
  withRgb({ code: 'C5', name: 'Cerulean', hex: '#01ACEB' }),
  withRgb({ code: 'C6', name: 'Cornflower Blue', hex: '#50AAF0' }),
  withRgb({ code: 'C7', name: 'Royal Blue', hex: '#3677D2' }),
  withRgb({ code: 'C8', name: 'Medium Blue', hex: '#0F54C0' }),
  withRgb({ code: 'C9', name: 'Slate Blue', hex: '#324BCA' }),
  withRgb({ code: 'C10', name: 'Sky Blue', hex: '#3EBCE2' }),
  withRgb({ code: 'C11', name: 'Turquoise', hex: '#28DDDE' }),
  withRgb({ code: 'C12', name: 'Navy', hex: '#1C334D' }),
  withRgb({ code: 'C13', name: 'Light Blue', hex: '#CDE8FF' }),
  withRgb({ code: 'C14', name: 'Cyan', hex: '#D5FDFF' }),
  withRgb({ code: 'C15', name: 'Dark Turquoise', hex: '#22C4C6' }),
  withRgb({ code: 'C16', name: 'Steel Blue', hex: '#1557A8' }),
  withRgb({ code: 'C17', name: 'Cyan 2', hex: '#04D1F6' }),
  withRgb({ code: 'C18', name: 'Dark Navy', hex: '#1D3344' }),
  withRgb({ code: 'C19', name: 'Teal Blue', hex: '#1887A2' }),
  withRgb({ code: 'C20', name: 'Azure Blue', hex: '#176DAF' }),
  withRgb({ code: 'C21', name: 'Powder Blue', hex: '#BEDDFF' }),
  withRgb({ code: 'C22', name: 'Cadet Blue', hex: '#67B4BE' }),
  withRgb({ code: 'C23', name: 'Alice Blue', hex: '#C8E2FF' }),
  withRgb({ code: 'C24', name: 'Light Steel Blue', hex: '#7CC4FF' }),
  withRgb({ code: 'C25', name: 'Powder Blue 2', hex: '#A9E5E5' }),
  withRgb({ code: 'C26', name: 'Dark Turquoise 2', hex: '#3CAED8' }),
  withRgb({ code: 'C27', name: 'Lavender Blue', hex: '#D3DFFA' }),
  withRgb({ code: 'C28', name: 'Periwinkle Blue', hex: '#BBCFED' }),
  withRgb({ code: 'C29', name: 'Midnight Blue', hex: '#34488E' }),
  withRgb({ code: 'D1', name: 'Periwinkle', hex: '#AEB4F2' }),
  withRgb({ code: 'D2', name: 'Medium Purple', hex: '#858EDD' }),
  withRgb({ code: 'D3', name: 'Royal Blue 2', hex: '#2F54AF' }),
  withRgb({ code: 'D4', name: 'Midnight Blue 2', hex: '#182A84' }),
  withRgb({ code: 'D5', name: 'Orchid', hex: '#B843C5' }),
  withRgb({ code: 'D6', name: 'Medium Orchid', hex: '#AC7BDE' }),
  withRgb({ code: 'D7', name: 'Dark Orchid', hex: '#8854B3' }),
  withRgb({ code: 'D8', name: 'Lavender', hex: '#E2D3FF' }),
  withRgb({ code: 'D9', name: 'Thistle', hex: '#D5B9F8' }),
  withRgb({ code: 'D10', name: 'Dark Purple', hex: '#361851' }),
  withRgb({ code: 'D11', name: 'Light Periwinkle', hex: '#B9BAE1' }),
  withRgb({ code: 'D12', name: 'Plum', hex: '#DE9AD4' }),
  withRgb({ code: 'D13', name: 'Magenta', hex: '#B90095' }),
  withRgb({ code: 'D14', name: 'Dark Magenta', hex: '#8B279B' }),
  withRgb({ code: 'D15', name: 'Indigo', hex: '#2F1F90' }),
  withRgb({ code: 'D16', name: 'Lavender 2', hex: '#E3E1EE' }),
  withRgb({ code: 'D17', name: 'Light Periwinkle 2', hex: '#C4D4F6' }),
  withRgb({ code: 'D18', name: 'Purple', hex: '#A45EC7' }),
  withRgb({ code: 'D19', name: 'Mauve', hex: '#D8C3D7' }),
  withRgb({ code: 'D20', name: 'Violet', hex: '#9C32B2' }),
  withRgb({ code: 'D21', name: 'Dark Violet', hex: '#9A009B' }),
  withRgb({ code: 'D22', name: 'Dark Indigo', hex: '#333A95' }),
  withRgb({ code: 'D23', name: 'Pale Lavender', hex: '#EBDAFC' }),
  withRgb({ code: 'D24', name: 'Cornflower', hex: '#7786E5' }),
  withRgb({ code: 'D25', name: 'Slate Blue 2', hex: '#494FC7' }),
  withRgb({ code: 'D26', name: 'Pale Violet', hex: '#DFC2F8' }),
  withRgb({ code: 'E1', name: 'Misty Rose', hex: '#FDD3CC' }),
  withRgb({ code: 'E2', name: 'Pink', hex: '#FEC0DF' }),
  withRgb({ code: 'E3', name: 'Hot Pink', hex: '#FFB7E7' }),
  withRgb({ code: 'E4', name: 'Deep Pink', hex: '#E8649E' }),
  withRgb({ code: 'E5', name: 'Magenta 2', hex: '#F551A2' }),
  withRgb({ code: 'E6', name: 'Crimson', hex: '#F13D74' }),
  withRgb({ code: 'E7', name: 'Maroon', hex: '#C63478' }),
  withRgb({ code: 'E8', name: 'Pale Pink', hex: '#FFDBE9' }),
  withRgb({ code: 'E9', name: 'Orchid Pink', hex: '#E970CC' }),
  withRgb({ code: 'E10', name: 'Fuchsia', hex: '#D33793' }),
  withRgb({ code: 'E11', name: 'Light Pink', hex: '#FCDDD2' }),
  withRgb({ code: 'E12', name: 'Light Pink 2', hex: '#F78FC3' }),
  withRgb({ code: 'E13', name: 'Dark Pink', hex: '#B5006D' }),
  withRgb({ code: 'E14', name: 'Peach 2', hex: '#FFD1BA' }),
  withRgb({ code: 'E15', name: 'Pink 2', hex: '#F8C7C9' }),
  withRgb({ code: 'E16', name: 'Seashell', hex: '#FFF3EB' }),
  withRgb({ code: 'E17', name: 'Lavender Blush', hex: '#FFE2EA' }),
  withRgb({ code: 'E18', name: 'Cotton Candy', hex: '#FFC7DB' }),
  withRgb({ code: 'E19', name: 'Pink 3', hex: '#FEBAD5' }),
  withRgb({ code: 'E20', name: 'Mauve 2', hex: '#D8C7D1' }),
  withRgb({ code: 'E21', name: 'Rose Taupe', hex: '#BD9DA1' }),
  withRgb({ code: 'E22', name: 'Mauve 3', hex: '#B785A1' }),
  withRgb({ code: 'E23', name: 'Dusty Purple', hex: '#937A8D' }),
  withRgb({ code: 'E24', name: 'Pale Orchid', hex: '#E1BCE8' }),
  withRgb({ code: 'F1', name: 'Light Coral', hex: '#FD957B' }),
  withRgb({ code: 'F2', name: 'Red', hex: '#FC3D46' }),
  withRgb({ code: 'F3', name: 'Tomato 2', hex: '#F74941' }),
  withRgb({ code: 'F4', name: 'Firebrick', hex: '#FC283C' }),
  withRgb({ code: 'F5', name: 'Crimson 2', hex: '#E7002F' }),
  withRgb({ code: 'F6', name: 'Dark Red', hex: '#943630' }),
  withRgb({ code: 'F7', name: 'Maroon 2', hex: '#971937' }),
  withRgb({ code: 'F8', name: 'Dark Red 2', hex: '#BC0028' }),
  withRgb({ code: 'F9', name: 'Rose', hex: '#E2677A' }),
  withRgb({ code: 'F10', name: 'Sienna', hex: '#8A4526' }),
  withRgb({ code: 'F11', name: 'Dark Brown', hex: '#5A2121' }),
  withRgb({ code: 'F12', name: 'Coral Red', hex: '#FD4E6A' }),
  withRgb({ code: 'F13', name: 'Tomato 3', hex: '#F35744' }),
  withRgb({ code: 'F14', name: 'Light Pink 3', hex: '#FFA9AD' }),
  withRgb({ code: 'F15', name: 'Crimson 3', hex: '#D30022' }),
  withRgb({ code: 'F16', name: 'Light Salmon 2', hex: '#FEC2A6' }),
  withRgb({ code: 'F17', name: 'Salmon 2', hex: '#E69C79' }),
  withRgb({ code: 'F18', name: 'Peru', hex: '#D37C46' }),
  withRgb({ code: 'F19', name: 'Indian Red', hex: '#C1444A' }),
  withRgb({ code: 'F20', name: 'Rosy Brown', hex: '#CD9391' }),
  withRgb({ code: 'F21', name: 'Pink 4', hex: '#F7B4C6' }),
  withRgb({ code: 'F22', name: 'Pink 5', hex: '#FDC0D0' }),
  withRgb({ code: 'F23', name: 'Coral 2', hex: '#F67E66' }),
  withRgb({ code: 'F24', name: 'Pale Violet Red', hex: '#E698AA' }),
  withRgb({ code: 'F25', name: 'Firebrick 2', hex: '#E54B4F' }),
  withRgb({ code: 'G1', name: 'Linen', hex: '#FFE2CE' }),
  withRgb({ code: 'G2', name: 'Peach Puff', hex: '#FFC4AA' }),
  withRgb({ code: 'G3', name: 'Wheat 2', hex: '#F4C3A5' }),
  withRgb({ code: 'G4', name: 'Tan', hex: '#E1B383' }),
  withRgb({ code: 'G5', name: 'Gold 2', hex: '#EDB045' }),
  withRgb({ code: 'G6', name: 'Orange 2', hex: '#E99C17' }),
  withRgb({ code: 'G7', name: 'Sienna 2', hex: '#9D5B3E' }),
  withRgb({ code: 'G8', name: 'Brown', hex: '#753832' }),
  withRgb({ code: 'G9', name: 'Tan 2', hex: '#E6B483' }),
  withRgb({ code: 'G10', name: 'Ochre', hex: '#D98C39' }),
  withRgb({ code: 'G11', name: 'Khaki 2', hex: '#E0C593' }),
  withRgb({ code: 'G12', name: 'Peach 3', hex: '#FFC890' }),
  withRgb({ code: 'G13', name: 'Brown 2', hex: '#B7714A' }),
  withRgb({ code: 'G14', name: 'Dark Tan', hex: '#8D614C' }),
  withRgb({ code: 'G15', name: 'Cornsilk', hex: '#FCF9E0' }),
  withRgb({ code: 'G16', name: 'Wheat 3', hex: '#F2D9BA' }),
  withRgb({ code: 'G17', name: 'Umber', hex: '#78524B' }),
  withRgb({ code: 'G18', name: 'Linen 2', hex: '#FFE4CC' }),
  withRgb({ code: 'G19', name: 'Chocolate', hex: '#E07935' }),
  withRgb({ code: 'G20', name: 'Rust', hex: '#A94023' }),
  withRgb({ code: 'G21', name: 'Tan 3', hex: '#B88558' }),
  withRgb({ code: 'H1', name: 'White Smoke', hex: '#FDFBFF' }),
  withRgb({ code: 'H2', name: 'White', hex: '#FEFFFF' }),
  withRgb({ code: 'H3', name: 'Silver', hex: '#B6B1BA' }),
  withRgb({ code: 'H4', name: 'Gray', hex: '#89858C' }),
  withRgb({ code: 'H5', name: 'Dim Gray', hex: '#48464E' }),
  withRgb({ code: 'H6', name: 'Dark Slate', hex: '#2F2B2F' }),
  withRgb({ code: 'H7', name: 'Black', hex: '#000000' }),
  withRgb({ code: 'H8', name: 'Lavender Blush 2', hex: '#E7D6DB' }),
  withRgb({ code: 'H9', name: 'Gainsboro', hex: '#EDEDED' }),
  withRgb({ code: 'H10', name: 'Snow', hex: '#EEE9EA' }),
  withRgb({ code: 'H11', name: 'Light Gray', hex: '#CECDD5' }),
  withRgb({ code: 'H12', name: 'Seashell 2', hex: '#FFF5ED' }),
  withRgb({ code: 'H13', name: 'Cornsilk 2', hex: '#F5ECD2' }),
  withRgb({ code: 'H14', name: 'Light Gray Green', hex: '#CFD7D3' }),
  withRgb({ code: 'H15', name: 'Dark Sea Green', hex: '#98A6A8' }),
  withRgb({ code: 'H16', name: 'Dark', hex: '#1D1414' }),
  withRgb({ code: 'H17', name: 'White Smoke 2', hex: '#F1EDED' }),
  withRgb({ code: 'H18', name: 'Ivory', hex: '#FFFDF0' }),
  withRgb({ code: 'H19', name: 'Old Lace', hex: '#F6EFE2' }),
  withRgb({ code: 'H20', name: 'Cadet Blue', hex: '#949FA3' }),
  withRgb({ code: 'H21', name: 'Light Yellow 2', hex: '#FFFBE1' }),
  withRgb({ code: 'H22', name: 'Light Steel', hex: '#CACAD4' }),
  withRgb({ code: 'H23', name: 'Dark Gray', hex: '#9A9D94' }),
  withRgb({ code: 'M1', name: 'Sage', hex: '#BCC6B8' }),
  withRgb({ code: 'M2', name: 'Fern', hex: '#8AA386' }),
  withRgb({ code: 'M3', name: 'Slate', hex: '#697D80' }),
  withRgb({ code: 'M4', name: 'Almond', hex: '#E3D2BC' }),
  withRgb({ code: 'M5', name: 'Pale Khaki', hex: '#D0CCAA' }),
  withRgb({ code: 'M6', name: 'Khaki', hex: '#B0A782' }),
  withRgb({ code: 'M7', name: 'Dark Khaki', hex: '#B4A497' }),
  withRgb({ code: 'M8', name: 'Rosy Brown 2', hex: '#B38281' }),
  withRgb({ code: 'M9', name: 'Khaki 3', hex: '#A58767' }),
  withRgb({ code: 'M10', name: 'Thistle 2', hex: '#C5B2BC' }),
  withRgb({ code: 'M11', name: 'Mauve 4', hex: '#9F7594' }),
  withRgb({ code: 'M12', name: 'Dark Brown 2', hex: '#644749' }),
  withRgb({ code: 'M13', name: 'Tan 4', hex: '#D19066' }),
  withRgb({ code: 'M14', name: 'Indian Red 2', hex: '#C77362' }),
  withRgb({ code: 'M15', name: 'Slate 2', hex: '#757D78' }),
  withRgb({ code: 'P1', name: 'Snow 2', hex: '#FCF7F8' }),
  withRgb({ code: 'P2', name: 'Silver 2', hex: '#B0A9AC' }),
  withRgb({ code: 'P3', name: 'Mint', hex: '#AFDCAB' }),
  withRgb({ code: 'P4', name: 'Salmon 3', hex: '#FEA49F' }),
  withRgb({ code: 'P5', name: 'Carrot', hex: '#EE8C3E' }),
  withRgb({ code: 'P6', name: 'Jade', hex: '#5FD0A7' }),
  withRgb({ code: 'P7', name: 'Coral 3', hex: '#EB9270' }),
  withRgb({ code: 'P8', name: 'Maize', hex: '#F0D958' }),
  withRgb({ code: 'P9', name: 'Gainsboro 2', hex: '#D9D9D9' }),
  withRgb({ code: 'P10', name: 'Lavender 3', hex: '#D9C7EA' }),
  withRgb({ code: 'P11', name: 'Cornsilk 3', hex: '#F3ECC9' }),
  withRgb({ code: 'P12', name: 'Alice Blue 2', hex: '#E6EEF2' }),
  withRgb({ code: 'P13', name: 'Light Steel Blue 2', hex: '#AACBEF' }),
  withRgb({ code: 'P14', name: 'Teal 2', hex: '#337680' }),
  withRgb({ code: 'P15', name: 'Viridian 2', hex: '#668575' }),
  withRgb({ code: 'P16', name: 'Butterscotch', hex: '#FEBF45' }),
  withRgb({ code: 'P17', name: 'Cheddar', hex: '#FEA324' }),
  withRgb({ code: 'P18', name: 'Peach 4', hex: '#FEB89F' }),
  withRgb({ code: 'P19', name: 'Light Ivory', hex: '#FFFEEC' }),
  withRgb({ code: 'P20', name: 'Pink 6', hex: '#FEBECF' }),
  withRgb({ code: 'P21', name: 'Pink 7', hex: '#ECBEBF' }),
  withRgb({ code: 'P22', name: 'Peach 5', hex: '#E4A89F' }),
  withRgb({ code: 'P23', name: 'Spice', hex: '#A56268' }),
  withRgb({ code: 'Q1', name: 'Orchid 2', hex: '#F2A5E8' }),
  withRgb({ code: 'Q2', name: 'Chartreuse 3', hex: '#E9EC91' }),
  withRgb({ code: 'Q3', name: 'Yellow 2', hex: '#FFFF00' }),
  withRgb({ code: 'Q4', name: 'Pink 8', hex: '#FFEBFA' }),
  withRgb({ code: 'Q5', name: 'Turquoise 2', hex: '#76CEDE' }),
  withRgb({ code: 'R1', name: 'Red 2', hex: '#D50D21' }),
  withRgb({ code: 'R2', name: 'Hot Pink 2', hex: '#F92F83' }),
  withRgb({ code: 'R3', name: 'Orange 3', hex: '#FD8324' }),
  withRgb({ code: 'R4', name: 'Yellow 3', hex: '#F8EC31' }),
  withRgb({ code: 'R5', name: 'Green 2', hex: '#35C75B' }),
  withRgb({ code: 'R6', name: 'Teal 3', hex: '#238891' }),
  withRgb({ code: 'R7', name: 'Blue', hex: '#19779D' }),
  withRgb({ code: 'R8', name: 'Royal Blue 3', hex: '#1A60C3' }),
  withRgb({ code: 'R9', name: 'Purple 2', hex: '#9A56B4' }),
  withRgb({ code: 'R10', name: 'Gold 3', hex: '#FFDB4C' }),
  withRgb({ code: 'R11', name: 'Pink 9', hex: '#FFEBFA' }),
  withRgb({ code: 'R12', name: 'Silver 3', hex: '#D8D5CE' }),
  withRgb({ code: 'R13', name: 'Dark Gray 2', hex: '#55514C' }),
  withRgb({ code: 'R14', name: 'Mint 2', hex: '#9FE4DF' }),
  withRgb({ code: 'R15', name: 'Light Blue 2', hex: '#77CEE9' }),
  withRgb({ code: 'R16', name: 'Turquoise 3', hex: '#3ECFCA' }),
  withRgb({ code: 'R17', name: 'Teal 4', hex: '#4A867A' }),
  withRgb({ code: 'R18', name: 'Green 3', hex: '#7FCD9D' }),
  withRgb({ code: 'R19', name: 'Lime 3', hex: '#CDE55D' }),
  withRgb({ code: 'R20', name: 'Peach 6', hex: '#E8C7B4' }),
  withRgb({ code: 'R21', name: 'Brown 3', hex: '#AD6F3C' }),
  withRgb({ code: 'R22', name: 'Dark Brown 3', hex: '#6C372F' }),
  withRgb({ code: 'R23', name: 'Gold 4', hex: '#FEB872' }),
  withRgb({ code: 'R24', name: 'Pink 10', hex: '#F3C1C0' }),
  withRgb({ code: 'R25', name: 'Indian Red 3', hex: '#C9675E' }),
  withRgb({ code: 'R26', name: 'Plum 2', hex: '#D293BE' }),
  withRgb({ code: 'R27', name: 'Pink 11', hex: '#EA8CB1' }),
  withRgb({ code: 'R28', name: 'Lavender 4', hex: '#9C87D6' }),
  withRgb({ code: 'T1', name: 'White 2', hex: '#FFFFFF' }),
  withRgb({ code: 'Y1', name: 'Pink 12', hex: '#FD6FB4' }),
  withRgb({ code: 'Y2', name: 'Peach 7', hex: '#FEB481' }),
  withRgb({ code: 'Y3', name: 'Lime 4', hex: '#D7FAA0' }),
  withRgb({ code: 'Y4', name: 'Light Blue 3', hex: '#8BDBFA' }),
  withRgb({ code: 'Y5', name: 'Orchid 3', hex: '#E987EA' }),
  withRgb({ code: 'ZG1', name: 'Pink 13', hex: '#DAABB3' }),
  withRgb({ code: 'ZG2', name: 'Tan 5', hex: '#D6AA87' }),
  withRgb({ code: 'ZG3', name: 'Khaki 4', hex: '#C1BD8D' }),
  withRgb({ code: 'ZG4', name: 'Lavender 5', hex: '#96869F' }),
  withRgb({ code: 'ZG5', name: 'Steel Blue 2', hex: '#8490A6' }),
  withRgb({ code: 'ZG6', name: 'Light Blue 4', hex: '#94BFE2' }),
  withRgb({ code: 'ZG7', name: 'Pink 14', hex: '#E2A9D2' }),
  withRgb({ code: 'ZG8', name: 'Lavender 6', hex: '#AB91C0' }),
];

const mardColors221 = mardColors291.slice(0, 221);

export const brandPalettes: Record<string, BrandPalette> = {
  perler: { name: 'perler', label: 'Perler · 59色', colors: perlerColors59 },
  'perler-82': { name: 'perler-82', label: 'Perler · 82色', colors: perlerColors82 },
  hama: { name: 'hama', label: 'Hama · 30色', colors: hamaColors30 },
  'hama-53': { name: 'hama-53', label: 'Hama · 53色', colors: hamaColors53 },
  artkal: { name: 'artkal', label: 'Artkal · 159色', colors: artkalColors },
  mard: { name: 'mard', label: 'MARD · 221色', colors: mardColors221 },
  'mard-291': { name: 'mard-291', label: 'MARD · 291色', colors: mardColors291 },
};

export const defaultBrand = 'mard';
