export interface BeadColor {
  code: string;
  name: string;
  hex: string;
}

export interface BrandPalette {
  name: string;
  label: string;
  colors: BeadColor[];
}

const perlerColors: BeadColor[] = [
  { code: 'P01', name: 'White', hex: '#F1F1F1' },
  { code: 'P02', name: 'Cream', hex: '#F5F0D7' },
  { code: 'P03', name: 'Yellow', hex: '#FFE100' },
  { code: 'P04', name: 'Orange', hex: '#FF6B1A' },
  { code: 'P05', name: 'Red', hex: '#E10600' },
  { code: 'P06', name: 'Pink', hex: '#FF8DB5' },
  { code: 'P07', name: 'Purple', hex: '#73389D' },
  { code: 'P08', name: 'Dark Blue', hex: '#0F3B8C' },
  { code: 'P09', name: 'Light Blue', hex: '#3370C0' },
  { code: 'P10', name: 'Dark Green', hex: '#114938' },
  { code: 'P11', name: 'Light Green', hex: '#56BA9F' },
  { code: 'P12', name: 'Brown', hex: '#6B4226' },
  { code: 'P13', name: 'Gray', hex: '#9B9B9B' },
  { code: 'P14', name: 'Black', hex: '#212121' },
  { code: 'P15', name: 'Blush', hex: '#F9CDC6' },
  { code: 'P16', name: 'Butterscotch', hex: '#FEBF45' },
  { code: 'P17', name: 'Cheddar', hex: '#FEA324' },
  { code: 'P18', name: 'Peach', hex: '#FEB89F' },
  { code: 'P19', name: 'Toothpaste', hex: '#FFFEEC' },
  { code: 'P20', name: 'Raspberry', hex: '#EC86D0' },
  { code: 'P21', name: 'Hot Coral', hex: '#ED6356' },
  { code: 'P22', name: 'Sand', hex: '#CC9966' },
  { code: 'P23', name: 'Spice', hex: '#A56268' },
  { code: 'P24', name: 'Turquoise', hex: '#299D8F' },
  { code: 'P25', name: 'Kiwi Lime', hex: '#AFDCAB' },
  { code: 'P26', name: 'Prickly Pear', hex: '#C53B7A' },
  { code: 'P27', name: 'Pastel Yellow', hex: '#F6EB61' },
  { code: 'P28', name: 'Pastel Lavender', hex: '#A05EB5' },
  { code: 'P29', name: 'Pastel Blue', hex: '#41B6E6' },
  { code: 'P30', name: 'Pastel Green', hex: '#87D839' },
  { code: 'P31', name: 'Plum', hex: '#53447D' },
  { code: 'P32', name: 'Mulberry', hex: '#F1A7DC' },
  { code: 'P33', name: 'Tangerine', hex: '#F6AD4C' },
  { code: 'P34', name: 'Neon Orange', hex: '#FF671F' },
  { code: 'P35', name: 'Neon Pink', hex: '#FF34B3' },
  { code: 'P36', name: 'Neon Green', hex: '#73D33C' },
  { code: 'P37', name: 'Neon Yellow', hex: '#CEDC00' },
  { code: 'P38', name: 'Bright Green', hex: '#24DE5B' },
  { code: 'P39', name: 'Dark Spruce', hex: '#00685E' },
  { code: 'P40', name: 'Evergreen', hex: '#183028' },
  { code: 'P41', name: 'Fruit Punch', hex: '#FF6D6A' },
  { code: 'P42', name: 'Bubblegum', hex: '#FCBFA9' },
  { code: 'P43', name: 'Cotton Candy', hex: '#F7CED7' },
  { code: 'P44', name: 'Mint', hex: '#9EE5B0' },
  { code: 'P45', name: 'Sky', hex: '#8DC8E8' },
  { code: 'P46', name: 'Lagoon', hex: '#71D8BF' },
  { code: 'P47', name: 'Fawn', hex: '#E1C078' },
  { code: 'P48', name: 'Honey', hex: '#FFE780' },
  { code: 'P49', name: 'Tan', hex: '#7B4D35' },
  { code: 'P50', name: 'Silver', hex: '#A09F9D' },
  { code: 'P51', name: 'Gold Metallic', hex: '#DEB947' },
  { code: 'P52', name: 'Light Blue', hex: '#5390D1' },
  { code: 'P53', name: 'Blue', hex: '#147BD1' },
  { code: 'P54', name: 'Turquoise Blue', hex: '#00AED6' },
  { code: 'P55', name: 'Slate', hex: '#767777' },
  { code: 'P56', name: 'Mocha', hex: '#B58150' },
  { code: 'P57', name: 'Mahogany', hex: '#5C4738' },
  { code: 'P58', name: 'Toothpaste', hex: '#93C8D4' },
  { code: 'P59', name: 'Wisteria', hex: '#C5B4E3' },
  { code: 'P60', name: 'Lavender', hex: '#A77BCA' },
  { code: 'P61', name: 'Iris', hex: '#64359B' },
  { code: 'P62', name: 'Midnight', hex: '#050849' },
  { code: 'P63', name: 'Robin\'s Egg', hex: '#59D5D8' },
  { code: 'P64', name: 'Steel Blue', hex: '#48A9C5' },
  { code: 'P65', name: 'Teal', hex: '#00B2A9' },
  { code: 'P66', name: 'Frost', hex: '#99D6EA' },
  { code: 'P67', name: 'Marshmallow', hex: '#F3CFB3' },
  { code: 'P68', name: 'Ginger', hex: '#B86125' },
  { code: 'P81', name: 'Light Gray', hex: '#EEEEEE' },
  { code: 'P82', name: 'Dark Gray', hex: '#6B6B6B' },
  { code: 'P83', name: 'Charcoal', hex: '#484949' },
  { code: 'P84', name: 'Copper', hex: '#9A5516' },
  { code: 'P85', name: 'Magenta', hex: '#DB2152' },
  { code: 'P86', name: 'Fuchsia', hex: '#DA1884' },
  { code: 'P91', name: 'Parrot Green', hex: '#067C81' },
  { code: 'P92', name: 'Lipstick Red', hex: '#BA0C2F' },
  { code: 'P101', name: 'Pearl Light Blue', hex: '#7AAEA2' },
  { code: 'P102', name: 'Pearl Pink', hex: '#FAAA8D' },
  { code: 'P103', name: 'Pearl Purple', hex: '#AB2556' },
  { code: 'P104', name: 'Pearl White', hex: '#F2F0A1' },
  { code: 'P105', name: 'Pearl Silver', hex: '#BAB8A2' },
  { code: 'P106', name: 'Pearl Gray', hex: '#888B8D' },
];

const hamaColors: BeadColor[] = [
  { code: 'H01', name: 'White', hex: '#ECEDED' },
  { code: 'H02', name: 'Cream', hex: '#F0E8B9' },
  { code: 'H03', name: 'Yellow', hex: '#F0B901' },
  { code: 'H04', name: 'Orange', hex: '#E64F27' },
  { code: 'H05', name: 'Red', hex: '#B63136' },
  { code: 'H06', name: 'Pink', hex: '#E1889F' },
  { code: 'H07', name: 'Purple', hex: '#694A82' },
  { code: 'H08', name: 'Dark Blue', hex: '#2C4690' },
  { code: 'H09', name: 'Light Blue', hex: '#305CB0' },
  { code: 'H10', name: 'Green', hex: '#256847' },
  { code: 'H11', name: 'Light Green', hex: '#49AE89' },
  { code: 'H12', name: 'Brown', hex: '#534137' },
  { code: 'H17', name: 'Grey', hex: '#83888A' },
  { code: 'H18', name: 'Black', hex: '#2E2F31' },
  { code: 'H20', name: 'Burgundy', hex: '#7F332A' },
  { code: 'H21', name: 'Tan', hex: '#A5693F' },
  { code: 'H22', name: 'Dark Red', hex: '#A52D36' },
  { code: 'H26', name: 'Flesh', hex: '#DE9B90' },
  { code: 'H27', name: 'Beige', hex: '#DEB48B' },
  { code: 'H28', name: 'Dark Green', hex: '#363F38' },
  { code: 'H29', name: 'Dark Pink', hex: '#B9395E' },
  { code: 'H30', name: 'Dark Brown', hex: '#592F38' },
  { code: 'H31', name: 'Steel Blue', hex: '#6797AE' },
  { code: 'H33', name: 'Neon Red', hex: '#FF3956' },
  { code: 'H43', name: 'Neon Yellow', hex: '#F0EA37' },
  { code: 'H44', name: 'Salmon', hex: '#EE6972' },
  { code: 'H45', name: 'Lavender', hex: '#886DB9' },
  { code: 'H46', name: 'Sky Blue', hex: '#629ED7' },
  { code: 'H47', name: 'Neon Green', hex: '#83CB70' },
  { code: 'H48', name: 'Neon Magenta', hex: '#CF70B7' },
  { code: 'H49', name: 'Turquoise', hex: '#4998BC' },
  { code: 'H60', name: 'Gold', hex: '#F49422' },
  { code: 'H70', name: 'Pastel Lavender', hex: '#B6B6D4' },
  { code: 'H71', name: 'Dark Grey', hex: '#464541' },
  { code: 'H75', name: 'Light Brown', hex: '#BF7B4D' },
  { code: 'H76', name: 'Chocolate', hex: '#663317' },
  { code: 'H77', name: 'Ivory', hex: '#EDE7DF' },
  { code: 'H78', name: 'Peach', hex: '#FFC99A' },
  { code: 'H79', name: 'Terracotta', hex: '#F08643' },
  { code: 'H82', name: 'Plum', hex: '#962F5C' },
  { code: 'H83', name: 'Teal', hex: '#0178A4' },
  { code: 'H84', name: 'Olive', hex: '#8B924C' },
  { code: 'H95', name: 'Light Pink', hex: '#F8CCE0' },
  { code: 'H96', name: 'Light Purple', hex: '#D4B1E3' },
  { code: 'H97', name: 'Baby Blue', hex: '#A2D3FE' },
  { code: 'H98', name: 'Mint', hex: '#9ADBB1' },
  { code: 'H101', name: 'Pale Green', hex: '#A9C39B' },
  { code: 'H102', name: 'Forest Green', hex: '#356B2D' },
  { code: 'H103', name: 'Lemon', hex: '#FFE660' },
  { code: 'H104', name: 'Lime', hex: '#BCD122' },
  { code: 'H105', name: 'Apricot', hex: '#FFAC78' },
  { code: 'H106', name: 'Periwinkle', hex: '#CCC5ED' },
  { code: 'H107', name: 'Cornflower', hex: '#6A87C1' },
];

const artkalColors: BeadColor[] = [
  { code: 'S01', name: 'White', hex: '#FFFFFF' },
  { code: 'S77', name: 'Ghost White', hex: '#EFEFEF' },
  { code: 'S78', name: 'Ash Gray', hex: '#D1D1D1' },
  { code: 'S79', name: 'Light Gray', hex: '#BBBCBC' },
  { code: 'S07', name: 'Gray', hex: '#9B9B9B' },
  { code: 'S43', name: 'Dark Gray', hex: '#767777' },
  { code: 'S89', name: 'Charcoal Gray', hex: '#484949' },
  { code: 'S69', name: 'Mine Shaft', hex: '#23282B' },
  { code: 'S13', name: 'Black', hex: '#000000' },
  { code: 'S42', name: 'Silver', hex: '#A09F9D' },
  { code: 'S41', name: 'Copper', hex: '#9A5516' },
  { code: 'S52', name: 'Picasso', hex: '#F2F0A1' },
  { code: 'S29', name: 'Pastel Yellow', hex: '#F6EB61' },
  { code: 'S14', name: 'Sandstorm', hex: '#FAE053' },
  { code: 'S27', name: 'Yellow', hex: '#FFD100' },
  { code: 'S48', name: 'Corn', hex: '#FFC72C' },
  { code: 'S86', name: 'Goldenrod', hex: '#EAAA00' },
  { code: 'S90', name: 'Pastel Orange', hex: '#FFC56E' },
  { code: 'S03', name: 'Tangerine', hex: '#F6AD4C' },
  { code: 'S39', name: 'Yellow Orange', hex: '#ED8B00' },
  { code: 'S56', name: 'Bright Carrot', hex: '#FF6A13' },
  { code: 'S04', name: 'Orange', hex: '#FF671F' },
  { code: 'S66', name: 'Blaze Orange', hex: '#F4633A' },
  { code: 'S87', name: 'Coral Red', hex: '#FF6D6A' },
  { code: 'S02', name: 'Burning Sand', hex: '#FFA38B' },
  { code: 'S50', name: 'Mandys Pink', hex: '#FAAA8D' },
  { code: 'S35', name: 'Mona Lisa', hex: '#F7CED7' },
  { code: 'S28', name: 'Lily Pink', hex: '#EAB8E4' },
  { code: 'S40', name: 'Carnation Pink', hex: '#F1A7DC' },
  { code: 'S06', name: 'Raspberry Pink', hex: '#EC86D0' },
  { code: 'S25', name: 'Hot Pink', hex: '#FF34B3' },
  { code: 'S26', name: 'Magenta', hex: '#DB2152' },
  { code: 'S05', name: 'Tall Poppy', hex: '#E10600' },
  { code: 'S34', name: 'Red', hex: '#BA0C2F' },
  { code: 'S58', name: 'Paprika', hex: '#A50034' },
  { code: 'S38', name: 'Burgundy', hex: '#AB2556' },
  { code: 'S49', name: 'Mulberry Wood', hex: '#72195F' },
  { code: 'S88', name: 'Dark Pink', hex: '#DA1884' },
  { code: 'S67', name: 'Vanilla', hex: '#F3CFB3' },
  { code: 'S18', name: 'Sand', hex: '#CC9966' },
  { code: 'S65', name: 'Canary', hex: '#F3EA5D' },
  { code: 'S46', name: 'Bright Green', hex: '#73D33C' },
  { code: 'S08', name: 'Emerald', hex: '#24DE5B' },
  { code: 'S61', name: 'Key Lemon Pie', hex: '#CEDC00' },
  { code: 'S70', name: 'Dark Algae', hex: '#9BBC11' },
  { code: 'S55', name: 'Pistachio', hex: '#ADDC91' },
  { code: 'S21', name: 'Pastel Green', hex: '#87D839' },
  { code: 'S20', name: 'Green', hex: '#249E6B' },
  { code: 'S71', name: 'Jade Green', hex: '#00852B' },
  { code: 'S62', name: 'Green Tea', hex: '#007C58' },
  { code: 'S09', name: 'Dark Green', hex: '#00685E' },
  { code: 'S91', name: 'Brunswick Green', hex: '#183028' },
  { code: 'S33', name: 'Maverick', hex: '#C5B4E3' },
  { code: 'S60', name: 'Lavender', hex: '#A77BCA' },
  { code: 'S12', name: 'Pastel Lavender', hex: '#A05EB5' },
  { code: 'S23', name: 'Royal Purple', hex: '#64359B' },
  { code: 'S59', name: 'Butterfly Bush', hex: '#4A1F87' },
  { code: 'S22', name: 'Purple', hex: '#330072' },
  { code: 'S64', name: 'Black Rock', hex: '#050849' },
  { code: 'S44', name: 'Sky Blue', hex: '#8DC8E8' },
  { code: 'S10', name: 'Baby Blue', hex: '#41B6E6' },
  { code: 'S53', name: 'Blue Enchantress', hex: '#69B3E7' },
  { code: 'S54', name: 'Light Blue', hex: '#0090DA' },
  { code: 'S24', name: 'True Blue', hex: '#147BD1' },
  { code: 'S11', name: 'Dark Blue', hex: '#003399' },
  { code: 'S30', name: 'Shadow Green', hex: '#99D6EA' },
  { code: 'S31', name: 'Sea Mist', hex: '#9EE5B0' },
  { code: 'S37', name: 'Blue-Green', hex: '#71D8BF' },
  { code: 'S72', name: 'Light Sea Blue', hex: '#59D5D8' },
  { code: 'S45', name: 'Medium Turquoise', hex: '#00B2A9' },
  { code: 'S76', name: 'Sea Blue', hex: '#00AEC7' },
  { code: 'S73', name: 'Steel Blue', hex: '#48A9C5' },
  { code: 'S74', name: 'Azure', hex: '#00AED6' },
  { code: 'S75', name: 'Dark Steel Blue', hex: '#0085AD' },
  { code: 'S19', name: 'Bubble Gum', hex: '#FCBFA9' },
  { code: 'S32', name: 'Beeswax', hex: '#FFE780' },
  { code: 'S68', name: 'Tan', hex: '#E1C078' },
  { code: 'S17', name: 'Light Brown', hex: '#7B4D35' },
  { code: 'S16', name: 'Brown', hex: '#5C4738' },
  { code: 'S15', name: 'Redwood', hex: '#793E2C' },
  { code: 'S83', name: 'Sienna', hex: '#B86125' },
  { code: 'S47', name: 'Marigold', hex: '#B47E00' },
  { code: 'S80', name: 'Dark Olive', hex: '#999B30' },
  { code: 'S63', name: 'Metallic Gold', hex: '#B8860B' },
  { code: 'S36', name: 'Old Pink', hex: '#C9809E' },
  { code: 'S51', name: 'Spring Sun', hex: '#FCFBCD' },
  { code: 'S81', name: 'Deer', hex: '#CDB277' },
  { code: 'S82', name: 'Clay', hex: '#B58150' },
  { code: 'S84', name: 'Deep Chestnut', hex: '#AA5761' },
  { code: 'S85', name: 'Red Wine', hex: '#42031A' },
  { code: 'S57', name: 'Buccaneer', hex: '#A4493D' },
  { code: 'S92', name: 'Dandelion', hex: '#DEB947' },
  { code: 'S93', name: 'Pale Skin', hex: '#DAB698' },
  { code: 'S94', name: 'Warm Blush', hex: '#F4A999' },
  { code: 'S95', name: 'Salmon', hex: '#EE7D67' },
  { code: 'S96', name: 'Apricot', hex: '#F08661' },
  { code: 'S97', name: 'Papaya', hex: '#D4722A' },
  { code: 'S98', name: 'Himalaya Blue', hex: '#64ACDF' },
  { code: 'S99', name: 'Waterfall', hex: '#64C2DC' },
  { code: 'S100', name: 'Lagoon', hex: '#4F9FB3' },
  { code: 'S101', name: 'Electric Blue', hex: '#3196DD' },
  { code: 'S102', name: 'Pool Blue', hex: '#1B6CB6' },
  { code: 'S103', name: 'Caribbean Blue', hex: '#083980' },
  { code: 'S104', name: 'Deep Water', hex: '#0A668B' },
  { code: 'S105', name: 'Petrol Blue', hex: '#085B6E' },
  { code: 'S106', name: 'Wedgewood Blue', hex: '#004E78' },
  { code: 'S107', name: 'Pond Blue', hex: '#005574' },
  { code: 'S108', name: 'Seashell Beige', hex: '#CCBE80' },
  { code: 'S109', name: 'Beige', hex: '#A49350' },
  { code: 'S110', name: 'Beach Beige', hex: '#9E883C' },
  { code: 'S111', name: 'Caffe Latte', hex: '#766C2B' },
  { code: 'S112', name: 'Oaktree Brown', hex: '#795F26' },
  { code: 'S113', name: 'Khaki', hex: '#BAB8A2' },
  { code: 'S119', name: 'Frosty Blue', hex: '#71C452' },
  { code: 'S120', name: 'Polar Mint', hex: '#66CC99' },
  { code: 'S122', name: 'Eucalyptus', hex: '#14C25B' },
  { code: 'S123', name: 'Clover Field', hex: '#18A818' },
  { code: 'S124', name: 'Pooltable Felt', hex: '#04552E' },
  { code: 'S125', name: 'Snake Green', hex: '#136B5A' },
  { code: 'S127', name: 'Marshmallow Rose', hex: '#D9B6D6' },
  { code: 'S128', name: 'Light Grape', hex: '#AD62A4' },
  { code: 'S129', name: 'Rosebud Pink', hex: '#E68CA3' },
  { code: 'S130', name: 'Fuchsia', hex: '#DE5479' },
  { code: 'S131', name: 'Candy Violet', hex: '#9E82BA' },
  { code: 'S132', name: 'Flamingo', hex: '#E8416B' },
  { code: 'S133', name: 'Pink Plum', hex: '#B7388F' },
  { code: 'S134', name: 'Amethyst', hex: '#581F7E' },
  { code: 'S135', name: 'Moonlight Blue', hex: '#8CA3D4' },
  { code: 'S136', name: 'Summer Rain', hex: '#9A9ACC' },
  { code: 'S137', name: 'Azure Blue', hex: '#5981C1' },
  { code: 'S138', name: 'Cornflower Blue', hex: '#4166B0' },
  { code: 'S139', name: 'Forget Me Not', hex: '#475FAB' },
  { code: 'S140', name: 'Indigo', hex: '#374593' },
  { code: 'S141', name: 'Horizon Blue', hex: '#3D56A5' },
  { code: 'S142', name: 'Cobalt', hex: '#294299' },
  { code: 'S143', name: 'Royal Blue', hex: '#25268A' },
  { code: 'S144', name: 'Marine', hex: '#1A2F6F' },
  { code: 'S145', name: 'Pale Yellow Moss', hex: '#D3C95D' },
  { code: 'S146', name: 'Bloodrose Red', hex: '#510918' },
  { code: 'S147', name: 'Spearmint', hex: '#64B39E' },
  { code: 'S148', name: 'Mocha', hex: '#634338' },
  { code: 'S149', name: 'Creme', hex: '#EDD39E' },
  { code: 'S150', name: 'Iris Violet', hex: '#6963AB' },
  { code: 'S151', name: 'Forest Green', hex: '#2B3F1F' },
  { code: 'S152', name: 'Lilac', hex: '#9791C5' },
  { code: 'S153', name: 'Pale Lilac', hex: '#B8BDE0' },
  { code: 'S154', name: 'Sahara Sand', hex: '#F9C898' },
  { code: 'S155', name: 'Sunkissed Teint', hex: '#C39069' },
  { code: 'S156', name: 'Steel Grey', hex: '#44505B' },
  { code: 'S157', name: 'Iron Grey', hex: '#3E4955' },
  { code: 'S158', name: 'Pepper', hex: '#202830' },
  { code: 'S159', name: 'Oslo Gray', hex: '#888B8D' },
];

const mardColors: BeadColor[] = [
  { code: 'A1', name: 'Lemon Chiffon', hex: '#FAF4C8' },
  { code: 'A2', name: 'Light Yellow', hex: '#FFFFD5' },
  { code: 'A3', name: 'Pale Yellow', hex: '#FEFF8B' },
  { code: 'A4', name: 'Yellow', hex: '#FBED56' },
  { code: 'A5', name: 'Golden Yellow', hex: '#F4D738' },
  { code: 'A6', name: 'Orange', hex: '#FEAC4C' },
  { code: 'A7', name: 'Dark Orange', hex: '#FE8B4C' },
  { code: 'A8', name: 'Gold', hex: '#FFDA45' },
  { code: 'A9', name: 'Light Salmon', hex: '#FF995B' },
  { code: 'A10', name: 'Coral', hex: '#F77C31' },
  { code: 'A11', name: 'Peach', hex: '#FFDD99' },
  { code: 'A12', name: 'Light Salmon', hex: '#FE9F72' },
  { code: 'A13', name: 'Moccasin', hex: '#FFC365' },
  { code: 'A14', name: 'Tomato', hex: '#FD543D' },
  { code: 'A15', name: 'Lemon', hex: '#FFF365' },
  { code: 'A16', name: 'Pale Gold', hex: '#FFFF9F' },
  { code: 'A17', name: 'Khaki', hex: '#FFE36E' },
  { code: 'A18', name: 'Wheat', hex: '#FEBE7D' },
  { code: 'A19', name: 'Salmon', hex: '#FD7C72' },
  { code: 'A20', name: 'Goldenrod', hex: '#FFD568' },
  { code: 'A21', name: 'Pale Goldenrod', hex: '#FFE395' },
  { code: 'A22', name: 'Green Yellow', hex: '#F4F57D' },
  { code: 'A23', name: 'Bisque', hex: '#E6C9B7' },
  { code: 'A24', name: 'Green Yellow 2', hex: '#F7F8A2' },
  { code: 'A25', name: 'Navajo White', hex: '#FFD67D' },
  { code: 'A26', name: 'Saffron', hex: '#FFC830' },
  { code: 'B1', name: 'Lime', hex: '#E6EE31' },
  { code: 'B2', name: 'Green', hex: '#63F347' },
  { code: 'B3', name: 'Pale Green', hex: '#9EF780' },
  { code: 'B4', name: 'Lime Green', hex: '#5DE035' },
  { code: 'B5', name: 'Spring Green', hex: '#35E352' },
  { code: 'B6', name: 'Medium Aquamarine', hex: '#65E2A6' },
  { code: 'B7', name: 'Sea Green', hex: '#3DAF80' },
  { code: 'B8', name: 'Forest Green', hex: '#1C9C4F' },
  { code: 'B9', name: 'Dark Green', hex: '#27523A' },
  { code: 'B10', name: 'Aquamarine', hex: '#95D3C2' },
  { code: 'B11', name: 'Olive Drab', hex: '#5D722A' },
  { code: 'B12', name: 'Dark Green 2', hex: '#166F41' },
  { code: 'B13', name: 'Chartreuse', hex: '#CAEB7B' },
  { code: 'B14', name: 'Green Yellow', hex: '#ADE946' },
  { code: 'B15', name: 'Dark Olive', hex: '#2E5132' },
  { code: 'B16', name: 'Light Green', hex: '#C5ED9C' },
  { code: 'B17', name: 'Yellow Green', hex: '#9BB13A' },
  { code: 'B18', name: 'Lime 2', hex: '#E6EE49' },
  { code: 'B19', name: 'Teal Green', hex: '#24B88C' },
  { code: 'B20', name: 'Mint Cream', hex: '#C2F0CC' },
  { code: 'B21', name: 'Teal', hex: '#156A6B' },
  { code: 'B22', name: 'Dark Slate', hex: '#0B3C43' },
  { code: 'B23', name: 'Dark Olive 2', hex: '#303A21' },
  { code: 'B24', name: 'Pale Green 2', hex: '#EEFCA5' },
  { code: 'B25', name: 'Viridian', hex: '#4E846D' },
  { code: 'B26', name: 'Olive', hex: '#8D7A35' },
  { code: 'B27', name: 'Pale Green 3', hex: '#CCE1AF' },
  { code: 'B28', name: 'Sea Green 2', hex: '#9EE5B9' },
  { code: 'B29', name: 'Chartreuse 2', hex: '#C5E254' },
  { code: 'B30', name: 'Pale Green 4', hex: '#E2FCB1' },
  { code: 'B31', name: 'Light Green 2', hex: '#B0E792' },
  { code: 'B32', name: 'Olive Green', hex: '#9CAB5A' },
  { code: 'C1', name: 'Honeydew', hex: '#E8FFE7' },
  { code: 'C2', name: 'Pale Turquoise', hex: '#A9F9FC' },
  { code: 'C3', name: 'Light Sky Blue', hex: '#A0E2FB' },
  { code: 'C4', name: 'Deep Sky Blue', hex: '#41CCFF' },
  { code: 'C5', name: 'Cerulean', hex: '#01ACEB' },
  { code: 'C6', name: 'Cornflower Blue', hex: '#50AAF0' },
  { code: 'C7', name: 'Royal Blue', hex: '#3677D2' },
  { code: 'C8', name: 'Medium Blue', hex: '#0F54C0' },
  { code: 'C9', name: 'Slate Blue', hex: '#324BCA' },
  { code: 'C10', name: 'Sky Blue', hex: '#3EBCE2' },
  { code: 'C11', name: 'Turquoise', hex: '#28DDDE' },
  { code: 'C12', name: 'Navy', hex: '#1C334D' },
  { code: 'C13', name: 'Light Blue', hex: '#CDE8FF' },
  { code: 'C14', name: 'Cyan', hex: '#D5FDFF' },
  { code: 'C15', name: 'Dark Turquoise', hex: '#22C4C6' },
  { code: 'C16', name: 'Steel Blue', hex: '#1557A8' },
  { code: 'C17', name: 'Cyan 2', hex: '#04D1F6' },
  { code: 'C18', name: 'Dark Navy', hex: '#1D3344' },
  { code: 'C19', name: 'Teal Blue', hex: '#1887A2' },
  { code: 'C20', name: 'Azure Blue', hex: '#176DAF' },
  { code: 'C21', name: 'Powder Blue', hex: '#BEDDFF' },
  { code: 'C22', name: 'Cadet Blue', hex: '#67B4BE' },
  { code: 'C23', name: 'Alice Blue', hex: '#C8E2FF' },
  { code: 'C24', name: 'Light Steel Blue', hex: '#7CC4FF' },
  { code: 'C25', name: 'Powder Blue 2', hex: '#A9E5E5' },
  { code: 'C26', name: 'Dark Turquoise 2', hex: '#3CAED8' },
  { code: 'C27', name: 'Lavender Blue', hex: '#D3DFFA' },
  { code: 'C28', name: 'Periwinkle Blue', hex: '#BBCFED' },
  { code: 'C29', name: 'Midnight Blue', hex: '#34488E' },
  { code: 'D1', name: 'Periwinkle', hex: '#AEB4F2' },
  { code: 'D2', name: 'Medium Purple', hex: '#858EDD' },
  { code: 'D3', name: 'Royal Blue 2', hex: '#2F54AF' },
  { code: 'D4', name: 'Midnight Blue 2', hex: '#182A84' },
  { code: 'D5', name: 'Orchid', hex: '#B843C5' },
  { code: 'D6', name: 'Medium Orchid', hex: '#AC7BDE' },
  { code: 'D7', name: 'Dark Orchid', hex: '#8854B3' },
  { code: 'D8', name: 'Lavender', hex: '#E2D3FF' },
  { code: 'D9', name: 'Thistle', hex: '#D5B9F8' },
  { code: 'D10', name: 'Dark Purple', hex: '#361851' },
  { code: 'D11', name: 'Light Periwinkle', hex: '#B9BAE1' },
  { code: 'D12', name: 'Plum', hex: '#DE9AD4' },
  { code: 'D13', name: 'Magenta', hex: '#B90095' },
  { code: 'D14', name: 'Dark Magenta', hex: '#8B279B' },
  { code: 'D15', name: 'Indigo', hex: '#2F1F90' },
  { code: 'D16', name: 'Lavender 2', hex: '#E3E1EE' },
  { code: 'D17', name: 'Light Periwinkle 2', hex: '#C4D4F6' },
  { code: 'D18', name: 'Purple', hex: '#A45EC7' },
  { code: 'D19', name: 'Mauve', hex: '#D8C3D7' },
  { code: 'D20', name: 'Violet', hex: '#9C32B2' },
  { code: 'D21', name: 'Dark Violet', hex: '#9A009B' },
  { code: 'D22', name: 'Dark Indigo', hex: '#333A95' },
  { code: 'D23', name: 'Pale Lavender', hex: '#EBDAFC' },
  { code: 'D24', name: 'Cornflower', hex: '#7786E5' },
  { code: 'D25', name: 'Slate Blue 2', hex: '#494FC7' },
  { code: 'D26', name: 'Pale Violet', hex: '#DFC2F8' },
  { code: 'E1', name: 'Misty Rose', hex: '#FDD3CC' },
  { code: 'E2', name: 'Pink', hex: '#FEC0DF' },
  { code: 'E3', name: 'Hot Pink', hex: '#FFB7E7' },
  { code: 'E4', name: 'Deep Pink', hex: '#E8649E' },
  { code: 'E5', name: 'Magenta 2', hex: '#F551A2' },
  { code: 'E6', name: 'Crimson', hex: '#F13D74' },
  { code: 'E7', name: 'Maroon', hex: '#C63478' },
  { code: 'E8', name: 'Pale Pink', hex: '#FFDBE9' },
  { code: 'E9', name: 'Orchid Pink', hex: '#E970CC' },
  { code: 'E10', name: 'Fuchsia', hex: '#D33793' },
  { code: 'E11', name: 'Light Pink', hex: '#FCDDD2' },
  { code: 'E12', name: 'Light Pink 2', hex: '#F78FC3' },
  { code: 'E13', name: 'Dark Pink', hex: '#B5006D' },
  { code: 'E14', name: 'Peach 2', hex: '#FFD1BA' },
  { code: 'E15', name: 'Pink 2', hex: '#F8C7C9' },
  { code: 'E16', name: 'Seashell', hex: '#FFF3EB' },
  { code: 'E17', name: 'Lavender Blush', hex: '#FFE2EA' },
  { code: 'E18', name: 'Cotton Candy', hex: '#FFC7DB' },
  { code: 'E19', name: 'Pink 3', hex: '#FEBAD5' },
  { code: 'E20', name: 'Mauve 2', hex: '#D8C7D1' },
  { code: 'E21', name: 'Rose Taupe', hex: '#BD9DA1' },
  { code: 'E22', name: 'Mauve 3', hex: '#B785A1' },
  { code: 'E23', name: 'Dusty Purple', hex: '#937A8D' },
  { code: 'E24', name: 'Pale Orchid', hex: '#E1BCE8' },
  { code: 'F1', name: 'Light Coral', hex: '#FD957B' },
  { code: 'F2', name: 'Red', hex: '#FC3D46' },
  { code: 'F3', name: 'Tomato 2', hex: '#F74941' },
  { code: 'F4', name: 'Firebrick', hex: '#FC283C' },
  { code: 'F5', name: 'Crimson 2', hex: '#E7002F' },
  { code: 'F6', name: 'Dark Red', hex: '#943630' },
  { code: 'F7', name: 'Maroon 2', hex: '#971937' },
  { code: 'F8', name: 'Dark Red 2', hex: '#BC0028' },
  { code: 'F9', name: 'Rose', hex: '#E2677A' },
  { code: 'F10', name: 'Sienna', hex: '#8A4526' },
  { code: 'F11', name: 'Dark Brown', hex: '#5A2121' },
  { code: 'F12', name: 'Coral Red', hex: '#FD4E6A' },
  { code: 'F13', name: 'Tomato 3', hex: '#F35744' },
  { code: 'F14', name: 'Light Pink 3', hex: '#FFA9AD' },
  { code: 'F15', name: 'Crimson 3', hex: '#D30022' },
  { code: 'F16', name: 'Light Salmon 2', hex: '#FEC2A6' },
  { code: 'F17', name: 'Salmon 2', hex: '#E69C79' },
  { code: 'F18', name: 'Peru', hex: '#D37C46' },
  { code: 'F19', name: 'Indian Red', hex: '#C1444A' },
  { code: 'F20', name: 'Rosy Brown', hex: '#CD9391' },
  { code: 'F21', name: 'Pink 4', hex: '#F7B4C6' },
  { code: 'F22', name: 'Pink 5', hex: '#FDC0D0' },
  { code: 'F23', name: 'Coral 2', hex: '#F67E66' },
  { code: 'F24', name: 'Pale Violet Red', hex: '#E698AA' },
  { code: 'F25', name: 'Firebrick 2', hex: '#E54B4F' },
  { code: 'G1', name: 'Linen', hex: '#FFE2CE' },
  { code: 'G2', name: 'Peach Puff', hex: '#FFC4AA' },
  { code: 'G3', name: 'Wheat 2', hex: '#F4C3A5' },
  { code: 'G4', name: 'Tan', hex: '#E1B383' },
  { code: 'G5', name: 'Gold 2', hex: '#EDB045' },
  { code: 'G6', name: 'Orange 2', hex: '#E99C17' },
  { code: 'G7', name: 'Sienna 2', hex: '#9D5B3E' },
  { code: 'G8', name: 'Brown', hex: '#753832' },
  { code: 'G9', name: 'Tan 2', hex: '#E6B483' },
  { code: 'G10', name: 'Ochre', hex: '#D98C39' },
  { code: 'G11', name: 'Khaki 2', hex: '#E0C593' },
  { code: 'G12', name: 'Peach 3', hex: '#FFC890' },
  { code: 'G13', name: 'Brown 2', hex: '#B7714A' },
  { code: 'G14', name: 'Dark Tan', hex: '#8D614C' },
  { code: 'G15', name: 'Cornsilk', hex: '#FCF9E0' },
  { code: 'G16', name: 'Wheat 3', hex: '#F2D9BA' },
  { code: 'G17', name: 'Umber', hex: '#78524B' },
  { code: 'G18', name: 'Linen 2', hex: '#FFE4CC' },
  { code: 'G19', name: 'Chocolate', hex: '#E07935' },
  { code: 'G20', name: 'Rust', hex: '#A94023' },
  { code: 'G21', name: 'Tan 3', hex: '#B88558' },
  { code: 'H1', name: 'White Smoke', hex: '#FDFBFF' },
  { code: 'H2', name: 'White', hex: '#FEFFFF' },
  { code: 'H3', name: 'Silver', hex: '#B6B1BA' },
  { code: 'H4', name: 'Gray', hex: '#89858C' },
  { code: 'H5', name: 'Dim Gray', hex: '#48464E' },
  { code: 'H6', name: 'Dark Slate', hex: '#2F2B2F' },
  { code: 'H7', name: 'Black', hex: '#000000' },
  { code: 'H8', name: 'Lavender Blush 2', hex: '#E7D6DB' },
  { code: 'H9', name: 'Gainsboro', hex: '#EDEDED' },
  { code: 'H10', name: 'Snow', hex: '#EEE9EA' },
  { code: 'H11', name: 'Light Gray', hex: '#CECDD5' },
  { code: 'H12', name: 'Seashell 2', hex: '#FFF5ED' },
  { code: 'H13', name: 'Cornsilk 2', hex: '#F5ECD2' },
  { code: 'H14', name: 'Light Gray Green', hex: '#CFD7D3' },
  { code: 'H15', name: 'Dark Sea Green', hex: '#98A6A8' },
  { code: 'H16', name: 'Dark', hex: '#1D1414' },
  { code: 'H17', name: 'White Smoke 2', hex: '#F1EDED' },
  { code: 'H18', name: 'Ivory', hex: '#FFFDF0' },
  { code: 'H19', name: 'Old Lace', hex: '#F6EFE2' },
  { code: 'H20', name: 'Cadet Blue', hex: '#949FA3' },
  { code: 'H21', name: 'Light Yellow 2', hex: '#FFFBE1' },
  { code: 'H22', name: 'Light Steel', hex: '#CACAD4' },
  { code: 'H23', name: 'Dark Gray', hex: '#9A9D94' },
  { code: 'M1', name: 'Sage', hex: '#BCC6B8' },
  { code: 'M2', name: 'Fern', hex: '#8AA386' },
  { code: 'M3', name: 'Slate', hex: '#697D80' },
  { code: 'M4', name: 'Almond', hex: '#E3D2BC' },
  { code: 'M5', name: 'Pale Khaki', hex: '#D0CCAA' },
  { code: 'M6', name: 'Khaki', hex: '#B0A782' },
  { code: 'M7', name: 'Dark Khaki', hex: '#B4A497' },
  { code: 'M8', name: 'Rosy Brown 2', hex: '#B38281' },
  { code: 'M9', name: 'Khaki 3', hex: '#A58767' },
  { code: 'M10', name: 'Thistle 2', hex: '#C5B2BC' },
  { code: 'M11', name: 'Mauve 4', hex: '#9F7594' },
  { code: 'M12', name: 'Dark Brown 2', hex: '#644749' },
  { code: 'M13', name: 'Tan 4', hex: '#D19066' },
  { code: 'M14', name: 'Indian Red 2', hex: '#C77362' },
  { code: 'M15', name: 'Slate 2', hex: '#757D78' },
  { code: 'P1', name: 'Snow 2', hex: '#FCF7F8' },
  { code: 'P2', name: 'Silver 2', hex: '#B0A9AC' },
  { code: 'P3', name: 'Mint', hex: '#AFDCAB' },
  { code: 'P4', name: 'Salmon 3', hex: '#FEA49F' },
  { code: 'P5', name: 'Carrot', hex: '#EE8C3E' },
  { code: 'P6', name: 'Jade', hex: '#5FD0A7' },
  { code: 'P7', name: 'Coral 3', hex: '#EB9270' },
  { code: 'P8', name: 'Maize', hex: '#F0D958' },
  { code: 'P9', name: 'Gainsboro 2', hex: '#D9D9D9' },
  { code: 'P10', name: 'Lavender 3', hex: '#D9C7EA' },
  { code: 'P11', name: 'Cornsilk 3', hex: '#F3ECC9' },
  { code: 'P12', name: 'Alice Blue 2', hex: '#E6EEF2' },
  { code: 'P13', name: 'Light Steel Blue 2', hex: '#AACBEF' },
  { code: 'P14', name: 'Teal 2', hex: '#337680' },
  { code: 'P15', name: 'Viridian 2', hex: '#668575' },
  { code: 'P16', name: 'Butterscotch', hex: '#FEBF45' },
  { code: 'P17', name: 'Cheddar', hex: '#FEA324' },
  { code: 'P18', name: 'Peach 4', hex: '#FEB89F' },
  { code: 'P19', name: 'Light Ivory', hex: '#FFFEEC' },
  { code: 'P20', name: 'Pink 6', hex: '#FEBECF' },
  { code: 'P21', name: 'Pink 7', hex: '#ECBEBF' },
  { code: 'P22', name: 'Peach 5', hex: '#E4A89F' },
  { code: 'P23', name: 'Spice', hex: '#A56268' },
  { code: 'Q1', name: 'Orchid 2', hex: '#F2A5E8' },
  { code: 'Q2', name: 'Chartreuse 3', hex: '#E9EC91' },
  { code: 'Q3', name: 'Yellow 2', hex: '#FFFF00' },
  { code: 'Q4', name: 'Pink 8', hex: '#FFEBFA' },
  { code: 'Q5', name: 'Turquoise 2', hex: '#76CEDE' },
  { code: 'R1', name: 'Red 2', hex: '#D50D21' },
  { code: 'R2', name: 'Hot Pink 2', hex: '#F92F83' },
  { code: 'R3', name: 'Orange 3', hex: '#FD8324' },
  { code: 'R4', name: 'Yellow 3', hex: '#F8EC31' },
  { code: 'R5', name: 'Green 2', hex: '#35C75B' },
  { code: 'R6', name: 'Teal 3', hex: '#238891' },
  { code: 'R7', name: 'Blue', hex: '#19779D' },
  { code: 'R8', name: 'Royal Blue 3', hex: '#1A60C3' },
  { code: 'R9', name: 'Purple 2', hex: '#9A56B4' },
  { code: 'R10', name: 'Gold 3', hex: '#FFDB4C' },
  { code: 'R11', name: 'Pink 9', hex: '#FFEBFA' },
  { code: 'R12', name: 'Silver 3', hex: '#D8D5CE' },
  { code: 'R13', name: 'Dark Gray 2', hex: '#55514C' },
  { code: 'R14', name: 'Mint 2', hex: '#9FE4DF' },
  { code: 'R15', name: 'Light Blue 2', hex: '#77CEE9' },
  { code: 'R16', name: 'Turquoise 3', hex: '#3ECFCA' },
  { code: 'R17', name: 'Teal 4', hex: '#4A867A' },
  { code: 'R18', name: 'Green 3', hex: '#7FCD9D' },
  { code: 'R19', name: 'Lime 3', hex: '#CDE55D' },
  { code: 'R20', name: 'Peach 6', hex: '#E8C7B4' },
  { code: 'R21', name: 'Brown 3', hex: '#AD6F3C' },
  { code: 'R22', name: 'Dark Brown 3', hex: '#6C372F' },
  { code: 'R23', name: 'Gold 4', hex: '#FEB872' },
  { code: 'R24', name: 'Pink 10', hex: '#F3C1C0' },
  { code: 'R25', name: 'Indian Red 3', hex: '#C9675E' },
  { code: 'R26', name: 'Plum 2', hex: '#D293BE' },
  { code: 'R27', name: 'Pink 11', hex: '#EA8CB1' },
  { code: 'R28', name: 'Lavender 4', hex: '#9C87D6' },
  { code: 'T1', name: 'White 2', hex: '#FFFFFF' },
  { code: 'Y1', name: 'Pink 12', hex: '#FD6FB4' },
  { code: 'Y2', name: 'Peach 7', hex: '#FEB481' },
  { code: 'Y3', name: 'Lime 4', hex: '#D7FAA0' },
  { code: 'Y4', name: 'Light Blue 3', hex: '#8BDBFA' },
  { code: 'Y5', name: 'Orchid 3', hex: '#E987EA' },
  { code: 'ZG1', name: 'Pink 13', hex: '#DAABB3' },
  { code: 'ZG2', name: 'Tan 5', hex: '#D6AA87' },
  { code: 'ZG3', name: 'Khaki 4', hex: '#C1BD8D' },
  { code: 'ZG4', name: 'Lavender 5', hex: '#96869F' },
  { code: 'ZG5', name: 'Steel Blue 2', hex: '#8490A6' },
  { code: 'ZG6', name: 'Light Blue 4', hex: '#94BFE2' },
  { code: 'ZG7', name: 'Pink 14', hex: '#E2A9D2' },
  { code: 'ZG8', name: 'Lavender 6', hex: '#AB91C0' },
];

export const brandPalettes: Record<string, BrandPalette> = {
  perler: {
    name: 'perler',
    label: 'Perler',
    colors: perlerColors,
  },
  hama: {
    name: 'hama',
    label: 'Hama',
    colors: hamaColors,
  },
  artkal: {
    name: 'artkal',
    label: 'Artkal',
    colors: artkalColors,
  },
  mard: {
    name: 'mard',
    label: 'MARD',
    colors: mardColors,
  },
};

export const defaultBrand = 'artkal';